env:
  browser: true
  es2021: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules: {
  no-console: off,
  linebreak-style: 0,
  import/extensions: off,
  no-await-in-loop: off,
}
